name: Deploy Client-Service

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD_TEST }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME_TEST }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t epgarzonr/clients-service:latest .
          docker push epgarzonr/clients-service:latest

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.AWS_SSH_KEY_TEST }}" > /tmp/key.pem
          chmod 400 /tmp/key.pem
          ssh -o StrictHostKeyChecking=no -i /tmp/key.pem ${{ secrets.AWS_USER_TEST }}@${{ secrets.AWS_HOST_TEST }} << 'EOF'
            docker pull epgarzonr/clients-service:latest

            docker-compose pull

            docker-compose up -d

            exit
          EOF
